apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetapi
  template:
    metadata:
      name: aspnetapi
      labels:
        app: aspnetapi
        aadpodidbinding: aspnetapi
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: aspnetapi
        image: abs-aspnetapi:v1.0.0
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
        ports:
        - containerPort: 8080               
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetapi
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: aspnetapi